#pragma config(Sensor, S1,     ,               sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     ,               sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     ,               sensorEV3_Gyro)
#pragma config(Motor,  motorA,          dir,           tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          esq,           tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          cancela,       tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float angulo;

//Dist para Achar Boneco
void anda_x_cm (float x){
	angulo = x*20.835;
	if (angulo >= 0){
		setMotorReversed(dir, false);
		setMotorReversed(esq, false);
} else {
	setMotorReversed(esq, true);
		setMotorReversed(dir, true);
}
	moveMotorTarget(dir, angulo, 50);
	moveMotorTarget(esq, angulo, 50);
	waitUntilMotorStop(dir);
	waitUntilMotorStop(esq);
}



task main()
{
	//setMotorTarget(cancela,20,10); //Posicao Inicial Cancela

		while(true){
			anda_x_cm (30);
			anda_x_cm	(-30);
		}

/*
		while(true){
		//	levanta cancela()
			setMotorTarget (cancela, 90, 20);
			//waitUntilMotorStop (cancela);
			delay(2000);

		//	baixar cancela()
			setMotorTarget (cancela, 20, 15);
			//waitUntilMotorStop (cancela);
			delay(2000);
		}
*/

}
