#pragma config(Motor,  motorA,          dir,           tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          esq,           tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          cancela,       tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define FRENTE 1
#define TRAS -1
#define ANTIHORARIO -1 //ESQUERDA
#define HORARIO 1 //DIREITA
#define POTENCIA 25 //30

/*Funcao andar reto
** Param: sentido
*/
void AndarReto (int sentido){
	setMotorSync(dir,esq,0,sentido*POTENCIA);
}

/*Funcao para girar robo
** Param: sentido do giro
*/
void GirarRobo(int degree, int sentido){
	//Keep looping until the gyro sensor reads greater
 //than 90 degrees (from latest reset position)
	 repeatUntil(getGyroHeading(S4) > degree ){

		 if(sentido == ANTIHORARIO){
			  //Point turn to the left
			  setMotorSpeed(esq, -50);
			  setMotorSpeed(dir, 50);
			 }else{
			 	//Point turn to the right
			  setMotorSpeed(esq, 50);
			  setMotorSpeed(dir, -50);
			}
	}

	if(sentido == FRENTE){
		AndarReto(FRENTE);
	}


	 //Stop the motors at the end of the turn
	 setMotorSpeed(esq, 0);
	 setMotorSpeed(dir, 0);
	 delay(100);
	 resetGyro(S4);
}


task main(){
int sentido;

	while(true){

		sentido = ANTIHORARIO;
		GirarRobo(90,sentido);
		delay(100);

		sentido = HORARIO;
		GirarRobo(90,sentido);
		delay(100);

		sentido = FRENTE;
		GirarRobo(90,sentido);
		delay(100);

		sentido = HORARIO;
		GirarRobo(180,sentido);
		delay(100);

	}

}


