#pragma config(Sensor, S2,     color,          sensorEV3_Color, modeEV3Color_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*

Intervalos APROXIMADOS RGB pelo sensor de cor
SEMPRE CALIBRAR ESSES VALORES ANTES DE TESTAR O ROBÔ

VERDE
R 6 - 10
G 15 - 38
B 11 - 15

VERMELHO
R 31 - 65
G 5 - 11
B 3 - 6

AMARELO
R 44 - 50
G 16 - 40
B 3 - 7

BRANCO
R 46 - 49
G 48 - 51
B 30 - 32

PRETO
R 0 - 10
G 0 - 10
B 0 - 10

AZUL (RAMPA)
R 7 - 8
G 16 - 16
B 20 - 21

*/

/*
** Funcao que retorna a cor de acordo com a calibracao RGB
** Params: nothing
*/
TLegoColors rightColor()
{
	//Creates variables to store the red, green, and blue values
	long int redValue;
	long int greenValue;
	long int blueValue;



	//Get the value of all three channels of the color sensor
	//and store it in the variables
	getColorRGB(S2, redValue, greenValue, blueValue);
	// se alguma COR for detectada
	if((redValue != 0) && (greenValue != 0) && (blueValue != 0)){
		// BRANCO
		if(redValue >= 40 && greenValue >= 40 && blueValue >= 30){
			return colorWhite;
			}else{
			// VERDE
			if((redValue <= 12) && (greenValue >= 25) && (blueValue <= 15)){
				return colorGreen;
				}else{
				// VERMELHO MALDITO
				if((redValue >= 35) && (greenValue <= 15) && (blueValue <= 12)){
					return colorRed;
					}else{
					// AMARELO
					if((redValue >= 30) && (greenValue >= 15) && (blueValue <= 10)){
						return colorYellow;
						}else{
						// AZUL
						if((redValue <= 15) && (greenValue >= 30) && (blueValue >= 30)){
							return colorBlue;
							}else{
							// PRETO
							if((redValue <= 10) && (greenValue <= 10) && (blueValue <= 10)){
								return colorBlack;
							}
						}
					}
				}
			}
		}
	}
	return colorNone;

}

task main(){
	TLegoColors cor = rightColor();
}
