#pragma config(Sensor, S2,     color,          sensorEV3_Color, modeEV3Color_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//Creates variables to store the red, green, and blue values
	long int redValue;
	long int greenValue;
	long int blueValue;
	string response;
	//Infinite Loop
	while (true)
	{
		//Get the value of all three channels of the color sensor
		//and store it in the variables
		eraseDisplay();
    delay(500);
		getColorRGB(S2, redValue, greenValue, blueValue);
		response = "";
		sprintf(response, "RED: %d", redValue);
		displayTextLine(1, response);
		response = "";
		sprintf(response, "GREEN: %d", greenValue);
		displayTextLine(2, response);
		response = "";
		sprintf(response, "BLUE: %d", blueValue);
    displayTextLine(3, response);
		sleep(5000);
	}



}
