#pragma config(Sensor, S2,     color,          sensorEV3_Color, modeEV3Color_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*Dados sensores (Émerson)
VERDE
R 3 - 5
G 10 - 15
B 4 - 7

VERMELHO
R 31 - 33
G 5
B 3 - 4

AMARELO
R 44 - 48
G 16 - 17
B 3 - 4

BRANCO
R 46 - 49
G 48 - 51
B 30 - 32

PRETO
R 3
G 3
B 2

AZUL (RAMPA)
R 5 - 9
G 14 - 30
B 15 - 34*/

task main()
{
	//Creates variables to store the red, green, and blue values
	long int redValue;
	long int greenValue;
	long int blueValue;
	string response;
	//Infinite Loop
	while (true)
	{
		//Get the value of all three channels of the color sensor
		//and store it in the variables
		eraseDisplay();
		delay(500);
		getColorRGB(S2, redValue, greenValue, blueValue);
		response = "";
		sprintf(response, "RED: %d", redValue);
		displayTextLine(1, response);
		response = "";
		sprintf(response, "GREEN: %d", greenValue);
		displayTextLine(2, response);
		response = "";
		sprintf(response, "BLUE: %d", blueValue);
		displayTextLine(3, response);
		sleep(5000);
	}



}
