#pragma config(Sensor, S3,     ,               sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true) //Infinite loop:
	{
		// display "Sensor Value: ##"
		displayCenteredTextLine(3, "Sensor Value: %d", SensorRaw[S3]);
		displayCenteredTextLine(5, "Sensor Value: %d", SensorValue[S3]);

		// Wait 100 milliseconds to help display correctly
		wait1Msec(1000);

		//Erase the display
		eraseDisplay();
	}



}
