#pragma config(Sensor, S1,     ult,            sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true){
	int a = getUSDistance(ult)	;
	displaySensorValues(2, ult);
  displayVariableValues(3,a);


	}
}
