#pragma config(Sensor, S1,     ult,            sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define DIST_BONECO 25

bool ultrassonico(){
	int vet[11];
	int i;
	int j;
  int aux;
  int k = 10 ;

	for (i=0; i<11; i++){
		vet[i] = getUSDistance(ult);
	}

	for(i = 0; i < 11; i++)
  {
     for(j = 0; j < k; j++)
     {
        if(vet[j] > vet[j+1])
        {
          aux = vet[j];
        	vet[j] = vet[j+1];
        	vet[j+1]=aux;
        }
     }
     k--;
  }

	if (vet[5] < DIST_BONECO){
		return true;
	}else{
		return false;
	}
}


task main()
{
	while(true){
	bool a = ultrassonico();
	//displaySensorValues(line4, ultrassonico);
	displayVariableValues(line5, a);
	}
}
