#pragma config(Motor,  motorA,          dir,           tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          esq,           tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          cancela,       tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define FRENTE 1
#define TRAS -1
#define ANTIHORARIO -1 //ESQUERDA
#define HORARIO 1 //DIREITA
#define POTENCIA 25 //30

/*Funcao andar reto
** Param: sentido
*/
void AndarReto (int sentido){
	//displayText(line1,"andar para frente");
	setMotorSync(dir,esq,0,sentido*POTENCIA);
}

/*Funcao para girar robo
** Param: sentido do giro
*/
int GirarRobo(int degree, int sentido){

 //Keep looping until the gyro sensor reads greater
 //than 90 degrees (from latest reset position)

/*    displayText(line1,"girar robo");
    displaySensorValues(line1,S4);
    displayVariableValues(line2,degree);
    displayText(line5,"sentido");
*/
    if(FRENTE){
  //      displayText(line4,"FRENTE");
        AndarReto(FRENTE);
    }

     repeatUntil(getGyroHeading(S4) > degree ){

         if(sentido == ANTIHORARIO){
    //       displayText(line3,"ANTIHORARIO");
           //Point turn to the left
           // setMotorSpeed(esq, -50);
           // setMotorSpeed(dir, 50);
         }else if(sentido == HORARIO){
         	displayText(line4,"HORARIO");
          //Point turn to the right
         	// setMotorSpeed(esq, 50);
          // setMotorSpeed(dir, -50);
        }
    }

    //Stop the motors at the end of the turn
    // setMotorSpeed(esq, 0);
    // setMotorSpeed(dir, 0);
     delay(100);
     resetGyro(S4);
}


task main(){
int sentido;


	while(true){

		sentido = ANTIHORARIO;
		GirarRobo(90,sentido);
		delay(100);

		sentido = HORARIO;
		GirarRobo(90,sentido);
		delay(100);

		sentido = FRENTE;
		GirarRobo(0,sentido);
		delay(100);

		sentido = HORARIO;
		GirarRobo(180,sentido);
		delay(100);

	}

}
